# Generated by Django 6.0.3 on 2026-03-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', '-submitted_at'], name='idx_attempts_user_date'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['-created_at'], name='idx_quizzes_created'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['is_published'], name='idx_quizzes_published'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_users_email'),
        ),
    ]
